// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTPnSPCOOB-vN5UffDaFSv9icbZaUyzQw',
    appId: '1:22168065282:web:b9d3763083f785bdf11e1b',
    messagingSenderId: '22168065282',
    projectId: 'ltnhung-4e40f',
    authDomain: 'ltnhung-4e40f.firebaseapp.com',
    databaseURL: 'https://ltnhung-4e40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ltnhung-4e40f.firebasestorage.app',
    measurementId: 'G-CBRGE0Z5L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVibgpC1wxhkHz9gJrM60Bkzosfw-Jry0',
    appId: '1:22168065282:android:43b222d672638df3f11e1b',
    messagingSenderId: '22168065282',
    projectId: 'ltnhung-4e40f',
    databaseURL: 'https://ltnhung-4e40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ltnhung-4e40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIKYUUd_otv0p-rw9ZB9-MzKl3_3NsyE',
    appId: '1:22168065282:ios:c8fddfce3c0dc834f11e1b',
    messagingSenderId: '22168065282',
    projectId: 'ltnhung-4e40f',
    databaseURL: 'https://ltnhung-4e40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ltnhung-4e40f.firebasestorage.app',
    iosBundleId: 'com.example.esp8266',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbIKYUUd_otv0p-rw9ZB9-MzKl3_3NsyE',
    appId: '1:22168065282:ios:c8fddfce3c0dc834f11e1b',
    messagingSenderId: '22168065282',
    projectId: 'ltnhung-4e40f',
    databaseURL: 'https://ltnhung-4e40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ltnhung-4e40f.firebasestorage.app',
    iosBundleId: 'com.example.esp8266',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTPnSPCOOB-vN5UffDaFSv9icbZaUyzQw',
    appId: '1:22168065282:web:4b43e642668cc710f11e1b',
    messagingSenderId: '22168065282',
    projectId: 'ltnhung-4e40f',
    authDomain: 'ltnhung-4e40f.firebaseapp.com',
    databaseURL: 'https://ltnhung-4e40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ltnhung-4e40f.firebasestorage.app',
    measurementId: 'G-LWNF6YC939',
  );
}
